Importing Pandas,Numpy,Matplotlib,Seaborn,and Warings libary

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [3]:
import pandas as pd

df = pd.read_csv('../Notebook/Data/stud.csv')
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [4]:
df.shape

(1000, 8)

In [5]:
from IPython.display import display
import pandas as pd

print('='*60)
print('📊 EXPLORATORY DATA ANALYSIS (EDA) SUMMARY')
print('='*60)

print('\n📌 Dataset Shape')
print(df.shape)

print('\n📌 First 5 Rows')
display(df.head())

print('\n📌 Last 5 Rows')
display(df.tail())

print('\n📌 Random Sample')
display(df.sample(5))

print('\n📌 Column Names')
display(pd.DataFrame(df.columns, columns=['Columns']))

print('\n📌 Data Types')
display(df.dtypes.to_frame('Data Type'))

print('\n📌 Dataset Information')
df.info()

print('\n📌 Missing Values')
display(df.isnull().sum().to_frame('Missing Values'))

print('\n📌 Duplicate Rows')
print(df.duplicated().sum())

print('\n📌 Numerical Summary')
display(df.describe().T)

print('\n📌 Categorical Summary')
display(df.describe(include='object').T)

print('\n📌 Correlation Matrix')
display(df.corr(numeric_only=True))

print('\n✅ EDA Completed Successfully!')

============================================================
📊 EXPLORATORY DATA ANALYSIS (EDA) SUMMARY
============================================================

📌 Dataset Shape
(1000, 8)

📌 First 5 Rows

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

📌 Last 5 Rows

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

📌 Random Sample

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
263,female,group E,high school,standard,none,99,93,90
26,male,group B,some college,standard,none,69,54,55
383,female,group E,some high school,free/reduced,none,38,49,45
837,female,group A,high school,standard,completed,75,82,79
953,male,group C,high school,standard,completed,58,52,54

📌 Column Names

                       Columns
0                       gender
1               race_ethnicity
2  parental_level_of_education
3                        lunch
4      test_preparation_course
5                   math_score
6                reading_score
7                writing_score

📌 Data Types

                            Data Type
gender                            str
race_ethnicity                    str
parental_level_of_education       str
lunch                             str
test_preparation_course           str
math_score                      int64
reading_score                   int64
writing_score                   int64

📌 Dataset Information
<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   str
 1   race_ethnicity               1000 non-null   str
 2   parental_level_of_education  1000 non-null   str
 3   lunch                        1000 non-null   str
 4   test_preparation_course      1000 non-null   str
 5   math_score                   1000 non-null   int64
 6   reading_score                1000 non-null   int64
 7   writing_score                1000 non-null   int64
dtypes: int64(3), str(5)
memory usage: 103.5 KB

📌 Missing Values

                             Missing Values
gender                                    0
race_ethnicity                            0
parental_level_of_education               0
lunch                                     0
test_preparation_course                   0
math_score                                0
reading_score                             0
writing_score                             0

📌 Duplicate Rows
0

📌 Numerical Summary

                count    mean        std   min    25%   50%   75%    max
math_score     1000.0  66.089  15.163080   0.0  57.00  66.0  77.0  100.0
reading_score  1000.0  69.169  14.600192  17.0  59.00  70.0  79.0  100.0
writing_score  1000.0  68.054  15.195657  10.0  57.75  69.0  79.0  100.0

📌 Categorical Summary

C:\Users\DEV_MANISH\AppData\Local\Temp\ipykernel_5152\1676703858.py:39: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(df.describe(include='object').T)

                            count unique           top freq
gender                       1000      2        female  518
race_ethnicity               1000      5       group C  319
parental_level_of_education  1000      6  some college  226
lunch                        1000      2      standard  645
test_preparation_course      1000      2          none  642

📌 Correlation Matrix

               math_score  reading_score  writing_score
math_score       1.000000       0.817580       0.802642
reading_score    0.817580       1.000000       0.954598
writing_score    0.802642       0.954598       1.000000

✅ EDA Completed Successfully!

In [14]:
print("Categories in 'gender' variable:",end = "")
print(df['gender' ].unique())

print("Categories in 'race/ethnicity' variable: ",end=" ")
print(df['race_ethnicity'].unique())

print("Categories in'parental level of education' variable:", end=" " )
print(df['parental_level_of_education'].unique())

print("Categories in 'lunch' variable:",end=" ")
print(df['lunch' ].unique())

print("Categories in 'test preparation course' variable:",end=" ")
print(df['test_preparation_course'].unique())

Categories in 'gender' variable:<ArrowStringArray>
['female', 'male']
Length: 2, dtype: str
Categories in 'race/ethnicity' variable:  <ArrowStringArray>
['group B', 'group C', 'group A', 'group D', 'group E']
Length: 5, dtype: str
Categories in'parental level of education' variable: <ArrowStringArray>
[ 'bachelor's degree',       'some college',    'master's degree',
 'associate's degree',        'high school',   'some high school']
Length: 6, dtype: str
Categories in 'lunch' variable: <ArrowStringArray>
['standard', 'free/reduced']
Length: 2, dtype: str
Categories in 'test preparation course' variable: <ArrowStringArray>
['none', 'completed']
Length: 2, dtype: str

In [19]:
numeical_feature = [feature for feature  in df.columns if df[feature].dtype !='O']
categorical_feature = [feature for feature  in df.columns if df[feature].dtype =='O']

## Adding columns for Total Score and Average

In [22]:
df['total_score'] = df['math_score']+df['reading_score']+df['writing_score']
df['average'] = (df['math_score']+df['reading_score']+df['writing_score'])/3

In [23]:
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,total_score,average
0,female,group B,bachelor's degree,standard,none,72,72,74,218,72.666667
1,female,group C,some college,standard,completed,69,90,88,247,82.333333
2,female,group B,master's degree,standard,none,90,95,93,278,92.666667
3,male,group A,associate's degree,free/reduced,none,47,57,44,148,49.333333
4,male,group C,some college,standard,none,76,78,75,229,76.333333

In [29]:
reading_full = (df['reading_score'] == 100).sum()

writing_full = (df['writing_score'] == 100).sum()

math_full = (df['math_score'] == 100).sum()

print("Reading full marks:", reading_full)
print("Writing full marks:", writing_full)
print("Math full marks:", math_full)

Reading full marks: 17
Writing full marks: 14
Math full marks: 7

In [30]:

reading_less_20 = df[df['reading_score'] <= 20]['average'].count()
writing_less_20 = df[df['writing_score'] <= 20]['average'].count()
math_less_20 = df[df['math_score'] <= 20]['average'].count()

print(f'Number of students with less than 20 marks in Maths: {math_less_20}')
print(f'Number of students with less than 20 marks in Writing: {writing_less_20}')
print(f'Number of students with less than 20 marks in Reading: {reading_less_20}')

Number of students with less than 20 marks in Maths: 4
Number of students with less than 20 marks in Writing: 3
Number of students with less than 20 marks in Reading: 1